### ISSUE TITLE
Add ReachNow (i.e., Transit + ReachNow)

### ISSUE THREAD

**Issue by evansiroky** [ibi-group/trimet-mod-otp#160]
The current UI has an option of Car2Go, but sometimes a result will show up with ReachNow. See below. At the very least there should be some kind of ReachNow icon added and perhaps a new option for ReachNow + Transit.

<img width="345" alt="screen shot 2019-02-21 at 3 04 59 pm" src="https://user-images.githubusercontent.com/3112493/53208024-3e93be00-35ea-11e9-88b2-6eed3a623ace.png">

**Comment by msrichardson** [comment]
I imagine this is due to car2go and ReachNow merging...  https://www.geekwire.com/2018/car2go-reachnow-car-sharing-services-merge-deal-auto-giants-daimler-bmw/

@fpurcell did we ever figure out ReachNow's api (or maybe that is no longer relevant due to the merger?)

**Comment by fpurcell** [comment]
We have ReachNow data ... separate API.  Not sure when they'll merge, nor if there will still be 2 separate APIs.

Another design question: should ReachNow and car2go be able to be toggled on & off separately?  I would think yes, since folks may not be a member of both...

**Comment by msrichardson** [comment]
At present, we should move forward with a separate toggle.

**Comment by fpurcell** [comment]
Don't need this no more...
