### ISSUE TITLE
Integrate e-scooters

### ISSUE THREAD

**Issue by msrichardson** [ibi-group/trimet-mod-otp#170]
Portland will be launching a second pilot (year-long this time), starting April 15.  Would like to incorporate into trip planner.  Still need to see APIs, which will help determine design, etc. questions.

**Comment by fpurcell** [comment]
City of Portland Info:
  - https://www.portlandoregon.gov/transportation/77294
  - https://github.com/CityofPortland

**Comment by fpurcell** [comment]
Note from Mike, who talked to CoP folks:

- GBFS will be available from the beginning and a separate 
- GeoJSON boundary will be available on PBOT’s GitHub. I suspect it will just be the CoP jurisdiction boundary but I guess we’ll see. 


**Two restrictions** in the new contract are “no scooters in city parks” and “no parking/staging scooters within 30 feet of a bus stop”. I’m guessing it will be difficult to prevent e-scooter routing through parks but maybe OTP has a method for handling that.

**Comment by fpurcell** [comment]
Read this in April (not sure the source, might be Willamette Week): 

Lime, Bolt and Spin were awarded permits to operate in town. 

Four more companies -- Clevr Mobility, Jump, Razor USA, Shared Technologies, Inc. -- are in “the final stages” of providing necessary information for a permit.

**Comment by fpurcell** [comment]
Closing, since we now have scooters
