### ISSUE TITLE
Scale-Based Sizing for Layer Icons

### ISSUE THREAD

**Issue by msrichardson** [ibi-group/trimet-mod-otp#174]
Please use scale-based sizing for layer icons.  

BIKETOWN is a good example of the benefit of this - map is cluttered when this layer is turned on, sometimes making it difficult to see legs of itinerary.

Erin from TriMet put together a nice set of rules for the icon scaling and tool tip additions. See: https://docs.google.com/spreadsheets/d/157irMLMX8m67ZrnV0doIlmUZiRbeDX7W07LurqiK5eo

**Comment by landonreed** [comment]
@msrichardson, I believe we can close this now. Assigning you for confirmation.

**Comment by msrichardson** [comment]
I agree, will reopen if discover otherwise.  Thanks.
