### ISSUE TITLE
Stop Viewer link in Stop Bubbles

### ISSUE THREAD

**Issue by msrichardson** [ibi-group/trimet-mod-otp#189]
We recently noticed a styling change to how the Stop Viewer is presented in the Stop Bubbles.  Formerly, it was hyperlinked text, and now it looks more like a button.

Old (from TriMet's beta, where we've renamed it)
![CropperCapture 392](https://user-images.githubusercontent.com/4853348/57560897-c366bc00-733d-11e9-94ea-4c13faea58f4.png)

New
![CropperCapture 393](https://user-images.githubusercontent.com/4853348/57560924-daa5a980-733d-11e9-93b5-25f106994b3a.png)

Further, the 'button' is too far left, abutting the Stop ID.

Do you know the genesis of this change?  If this is the new style, at the very least can a buffer be placed between the Stop ID and this feature?

**Comment by landonreed** [comment]
I'm not exactly sure how this was introduced, but my best guess is that some CSS styling got jumbled during the recent push to move some of the TriMet code back into the main otp-react-redux library. @evansiroky, does this seem like a possibility to you/do you have any insights?
