### ISSUE TITLE
Bicycling trip durations

### ISSUE THREAD

**Issue by msrichardson** [ibi-group/trimet-mod-otp#202]
Please check the bicycling trip duration calculation on the dev site, they are currently showing as taking _much_ longer than normal.

(start/end may not be _exactly_ the same, but are close, for the example below)

TriMet's beta planner (5 min; does not include latest updates): https://betaplanner.trimet.org/map/#/?fromPlace=214%20W%20Burnside%20St%2C%20Portland%2C%20OR%2C%20USA%2097204%3A%3A45.52308191348417%2C-122.67251371682498&toPlace=300%20SW%2012th%20Ave%2C%20Portland%2C%20OR%2C%20USA%2097205%3A%3A45.52289399174057%2C-122.68282414818552&date=2019-06-03&time=15%3A01&arriveBy=false&mode=BICYCLE&showIntermediateStops=true&optimize=SAFE&bikeSpeed=3.58&ignoreRealtimeUpdates=true&companies=

Dev site (1 hr, 9 min):  https://trimet-mod-dev.ibi-transit.com/#/?fromPlace=214%20W%20Burnside%20St%2C%20Portland%2C%20OR%2C%20USA%2097204%3A%3A45.52304432918567%2C-122.67269611096705&toPlace=300%20SW%2012th%20Ave%2C%20Portland%2C%20OR%2C%20USA%2097205%3A%3A45.52289399174057%2C-122.68283486340077&date=2019-06-03&time=15%3A02&arriveBy=false&mode=BICYCLE&showIntermediateStops=true&optimize=SAFE&bikeSpeed=3.58&ignoreRealtimeUpdates=true&companies=

**Comment by landonreed** [comment]
As @mosteele mentioned in the check-in, this appears to have resolved itself somehow. Closing for now, but let's re-open if we see it again so we can attempt to isolate the issue.
