### ISSUE TITLE
Print View: car2go, eScooters, and BIKETOWN

### ISSUE THREAD

**Issue by msrichardson** [ibi-group/trimet-mod-otp#238]
The print view versions for car2go, eScooter, and BIKETOWN legs do not necessarily match the itinerary versions and could potentially be confusing.  Please split ticket as appropriate.

**car2go**
[_Print view_](https://modbeta.trimet.org/map-veh/#/print/?ui_activeSearch=96gwy3fc9&ui_activeItinerary=0&fromPlace=1752%20SE%20Ladd%20Ave%2C%20Portland%2C%20OR%2C%20USA%2097214%3A%3A45.51043713898763%2C-122.65101946419323&toPlace=4849%20NE%20Mason%20St%2C%20Portland%2C%20OR%2C%20USA%2097218%3A%3A45.55300607630593%2C-122.61256722355365&date=2019-08-09&time=17%3A07&arriveBy=false&mode=BUS%2CTRAM%2CRAIL%2CGONDOLA%2CCAR_RENT%2CWALK&showIntermediateStops=true&optimize=QUICK&ignoreRealtimeUpdates=true&companies=CAR2GO&minTransitDistance=50%25&searchTimeout=10000&onlyTransitTrips=true) could be misinterpreted as using one's own vehicle.  Using example below, consider changing to "Walk to 4219 NE Fremont St" and "Drive car2go 628LLK to 4849 NE Mason St"
![car2go_Print](https://user-images.githubusercontent.com/4853348/62904825-b8e10780-bd1c-11e9-84b7-ace04e995e68.png)

[_Itinerary view_](https://modbeta.trimet.org/map-veh/#/?ui_activeSearch=96gwy3fc9&ui_activeItinerary=0&fromPlace=1752%20SE%20Ladd%20Ave%2C%20Portland%2C%20OR%2C%20USA%2097214%3A%3A45.51043713898763%2C-122.65101946419323&toPlace=4849%20NE%20Mason%20St%2C%20Portland%2C%20OR%2C%20USA%2097218%3A%3A45.55300607630593%2C-122.61256722355365&date=2019-08-09&time=17%3A07&arriveBy=false&mode=BUS%2CTRAM%2CRAIL%2CGONDOLA%2CCAR_RENT%2CWALK&showIntermediateStops=true&optimize=QUICK&ignoreRealtimeUpdates=true&companies=CAR2GO&minTransitDistance=50%25&searchTimeout=10000&onlyTransitTrips=true)
![car2go_Itin](https://user-images.githubusercontent.com/4853348/62904836-bd0d2500-bd1c-11e9-8f48-6624ab57a7b2.png)

**eScooters**
[_Print view_](https://modbeta.trimet.org/map-veh/#/print/?ui_activeSearch=bafnv2ocf&ui_activeItinerary=0&fromPlace=1752%20SE%20Ladd%20Ave%2C%20Portland%2C%20OR%2C%20USA%2097214%3A%3A45.51043713898763%2C-122.65101946419323&toPlace=4849%20NE%20Mason%20St%2C%20Portland%2C%20OR%2C%20USA%2097218%3A%3A45.55300607630593%2C-122.61256722355365&date=2019-08-09&time=17%3A07&arriveBy=false&mode=BUS%2CTRAM%2CRAIL%2CGONDOLA%2CMICROMOBILITY_RENT&showIntermediateStops=true&optimize=QUICK&maxWalkDistance=4828&maxEScooterDistance=4828&ignoreRealtimeUpdates=true&companies=BOLT%2CLIME%2CRAZOR%2CSPIN) uses scooter "name" (which we found doesn't always match reality) and does not indicate the scooter company.
![Scooter_Print](https://user-images.githubusercontent.com/4853348/62904843-c26a6f80-bd1c-11e9-9104-dc3f021fc250.png)

[_Itinerary view_](https://modbeta.trimet.org/map-veh/#/?ui_activeSearch=bafnv2ocf&ui_activeItinerary=0&fromPlace=1752%20SE%20Ladd%20Ave%2C%20Portland%2C%20OR%2C%20USA%2097214%3A%3A45.51043713898763%2C-122.65101946419323&toPlace=4849%20NE%20Mason%20St%2C%20Portland%2C%20OR%2C%20USA%2097218%3A%3A45.55300607630593%2C-122.61256722355365&date=2019-08-09&time=17%3A07&arriveBy=false&mode=BUS%2CTRAM%2CRAIL%2CGONDOLA%2CMICROMOBILITY_RENT&showIntermediateStops=true&optimize=QUICK&maxWalkDistance=4828&maxEScooterDistance=4828&ignoreRealtimeUpdates=true&companies=BOLT%2CLIME%2CRAZOR%2CSPIN)
![Scooter_Itin](https://user-images.githubusercontent.com/4853348/62904849-c72f2380-bd1c-11e9-8a1f-ff5fa9907ee3.png)

**BIKETOWN**
Of the three, this one is the closest, especially as in this example, one is walking to a corral, but otherwise the [_print view_](https://modbeta.trimet.org/map-veh/#/print/?ui_activeSearch=oqqbyhixw&ui_activeItinerary=0&fromPlace=2355%20NW%2021st%20Pl%2C%20Portland%2C%20OR%2C%20USA%2097210%3A%3A45.539781890816336%2C-122.69677164056363&toPlace=4514%20NE%20Davis%20St%2C%20Portland%2C%20OR%2C%20USA%2097213%3A%3A45.524449964858896%2C-122.61574749054903&date=2019-08-09&time=17%3A07&arriveBy=false&mode=BUS%2CTRAM%2CRAIL%2CGONDOLA%2CBICYCLE_RENT&showIntermediateStops=true&maxWalkDistance=4828&maxBikeDistance=4828&optimize=SAFE&bikeSpeed=3.58&ignoreRealtimeUpdates=true&companies=BIKETOWN) could be misinterpreted as using one's own bike. 
![BIKETOWN_Print](https://user-images.githubusercontent.com/4853348/62904852-cbf3d780-bd1c-11e9-8500-c249cb79ec40.png)

[_Itinerary view_](https://modbeta.trimet.org/map-veh/#/?ui_activeSearch=oqqbyhixw&ui_activeItinerary=0&fromPlace=2355%20NW%2021st%20Pl%2C%20Portland%2C%20OR%2C%20USA%2097210%3A%3A45.539781890816336%2C-122.69677164056363&toPlace=4514%20NE%20Davis%20St%2C%20Portland%2C%20OR%2C%20USA%2097213%3A%3A45.524449964858896%2C-122.61574749054903&date=2019-08-09&time=17%3A07&arriveBy=false&mode=BUS%2CTRAM%2CRAIL%2CGONDOLA%2CBICYCLE_RENT&showIntermediateStops=true&maxWalkDistance=4828&maxBikeDistance=4828&optimize=SAFE&bikeSpeed=3.58&ignoreRealtimeUpdates=true&companies=BIKETOWN)
![BIKETOWN_Itin](https://user-images.githubusercontent.com/4853348/62904853-cf875e80-bd1c-11e9-98d1-b7c9c1474e2d.png)

**Comment by landonreed** [comment]
There is one item here that can be fixed relatively easily to match the web view: the print view's "walk to scooter_id" can be modified to match the "Walk to Bolt eScooter" that is shown in the standard web view. The rest of the instructions are actually the same between web and print views. The only differences are:

- the company logo is not being used
- the "pick up" text is omitted
- the distance is not included (e.g. "Bicycle 1.9 miles to SW Harvey" -> "Bicycle to SW Harvey")

To resolve this issue, I can implement the fix I described in the first paragraph as well as any of the above items I listed. I think adding the logo, might be the most effective. It might make sense to add the "pick up" text, but I would need some direction on how you want that to appear in the print view.

Let me know if you think I've missed something here.

**Comment by msrichardson** [comment]
Yes, in general they are the same, but if the plan was made on someone else's behalf, and they only have the print view, it isn't clear a third party provider's vehicle is being used.  To that end, we'd like to see the following on the print views for these three modes:

**eScooters**
Please proceed with your suggestion to replace the 'walk to scooter_id' with 'Walk to {Company} eScooter" that is shown in the itinerary view.

**BIKETOWN**
Replace the 'Bicycle to XYZ' with either 'Ride BIKETOWN bicycle to XYZ' or 'Take BIKETOWN bicycle to XYZ'.

**car2go**
Either 1) amend both the walk and drive 'instructions as noted in above in the original request or 2) just replace the 'Walk to XYZ' with 'Walk to car2go {car name} at {address of car location}'.  [Using example above, this would result in 'Walk to car2go 628LLK at 4219 NE Fremont St'.]

The other items you mentioned would ultimately be nice to incorporate, but at this point we are just seeking the minimum changes necessary for clarity.  Thank you!

**Comment by msrichardson** [comment]
@landonreed  I thought we were only going to update the text at this time, and not include company logos, or possibly I am misinterpreting this item?  https://github.com/ibi-group/trimet-mod-otp/pull/240

**Comment by landonreed** [comment]
@msrichardson, no, you're interpreting #240 correctly. I believe @evansiroky probably judged the amount of time required to fix the icons to be relatively small and went ahead with the icons fix. Is that OK from TriMet's perspective? Apologies for the confusion.

**Comment by msrichardson** [comment]
Thanks, and I believe so (we'd have to see it, but I'm sure it will be fine).
