### ISSUE TITLE
Change eScooter to E-scooter

### ISSUE THREAD

**Issue by msrichardson** [ibi-group/trimet-mod-otp#246]
In all places that are not 'controlled by config file, such as in the itinerary results,  please change eScooter to E-scooter (to be consistent with City of Portland and industry standard naming conventions).

**Comment by fpurcell** [comment]
Hey Landon ... there's a 'language' section in config.yml (e.g., we use that to change the 'Route Viewer' into 'TransitTracker', etc...), where naming mode types like scooters would be a good thing. 

https://modbeta.trimet.org/map/config.yml
