### ISSUE TITLE
Itinerary view not filling full width of menu frame

### ISSUE THREAD

**Issue by jon-campbell-ibigroup** [ibi-group/trimet-mod-otp#282]
Depending on size of screen, there is sometimes excess white space on one or both sides of the itinerary details. Would recommend updating so itinerary width resizes based on dimensions of the menu.
![image](https://user-images.githubusercontent.com/20230489/98613714-b49ef380-22ab-11eb-8f2b-e07707c50b85.png)

**Comment by binh-dam-ibigroup** [comment]
Closing this issue, now that https://github.com/ibi-group/configurations/pull/102 and https://github.com/opentripplanner/otp-react-redux/pull/279 have been merged.
