### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by stefanocudini** [ibi-group/trimet-mod-otp#288]
hi I was wondering about future developments if there is a defined roadmap for this project

I was trying to figure out if internationalization was one of the milestones

so if I do it in my fork of this project

many tnks

**Comment by landonreed** [comment]
Hi @stefanocudini, we do have some work planned to internationalize this project (along with https://github.com/opentripplanner/otp-react-redux/ and https://github.com/opentripplanner/otp-ui, which it relies on).

This work is not scheduled to be completed until early fall 2021, but you can watch the [otp-react-redux releases page](https://github.com/opentripplanner/otp-react-redux/releases) to see if internationalization gets completed sooner (we haven't yet planned out our timeline for this work yet).

As for a larger roadmap, we don't have one currently published, but will consider adding one to otp-react-redux and will let you know if we do so.
